/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Class.Round_Robin;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.ArrayList;
import java.util.TimerTask;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTextField;



    
/**
 *
 * @author ATHER
 */
public class F1 extends javax.swing.JFrame {

    ArrayList<JLabel> name = new ArrayList<JLabel>();
    ArrayList<JPanel> smallpanal = new ArrayList<JPanel>();
    JPanel largepanel = new JPanel();
    FlowLayout f = new FlowLayout();
    BorderLayout B = new BorderLayout();
    
    ArrayList<JTextField> alltxt = new ArrayList<JTextField>();
    ArrayList<JSeparator> allsep = new ArrayList<JSeparator>();
    /**
     * Creates new form F1
     */
    public F1() {
        initComponents();
        setLocationRelativeTo(this);
        Assigntxtsep();
        Hidden();
        
        //-------------
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        MID = new javax.swing.JPanel();
        P1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        txtNoP = new javax.swing.JTextField();
        sep1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtq = new javax.swing.JTextField();
        sep2 = new javax.swing.JSeparator();
        P3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtpname1 = new javax.swing.JTextField();
        navname1 = new javax.swing.JSeparator();
        txtpat1 = new javax.swing.JTextField();
        navpat1 = new javax.swing.JSeparator();
        txtpbt1 = new javax.swing.JTextField();
        navpbt1 = new javax.swing.JSeparator();
        txtpname2 = new javax.swing.JTextField();
        navname2 = new javax.swing.JSeparator();
        txtpname3 = new javax.swing.JTextField();
        navname3 = new javax.swing.JSeparator();
        txtpname4 = new javax.swing.JTextField();
        navname4 = new javax.swing.JSeparator();
        txtpname5 = new javax.swing.JTextField();
        navname5 = new javax.swing.JSeparator();
        txtpname6 = new javax.swing.JTextField();
        navname6 = new javax.swing.JSeparator();
        txtpname7 = new javax.swing.JTextField();
        navname7 = new javax.swing.JSeparator();
        txtpat2 = new javax.swing.JTextField();
        navpat2 = new javax.swing.JSeparator();
        txtpat3 = new javax.swing.JTextField();
        navpat3 = new javax.swing.JSeparator();
        txtpat4 = new javax.swing.JTextField();
        navpat4 = new javax.swing.JSeparator();
        txtpat5 = new javax.swing.JTextField();
        navpat5 = new javax.swing.JSeparator();
        txtpat6 = new javax.swing.JTextField();
        navpat6 = new javax.swing.JSeparator();
        txtpat7 = new javax.swing.JTextField();
        navpat7 = new javax.swing.JSeparator();
        txtpbt2 = new javax.swing.JTextField();
        navpbt2 = new javax.swing.JSeparator();
        txtpbt3 = new javax.swing.JTextField();
        navpbt3 = new javax.swing.JSeparator();
        txtpbt4 = new javax.swing.JTextField();
        navpbt4 = new javax.swing.JSeparator();
        txtpbt5 = new javax.swing.JTextField();
        navpbt5 = new javax.swing.JSeparator();
        txtpbt6 = new javax.swing.JTextField();
        navpbt6 = new javax.swing.JSeparator();
        txtpbt7 = new javax.swing.JTextField();
        navpbt7 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        P4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        exit2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        avgw = new javax.swing.JLabel();
        avgt = new javax.swing.JLabel();
        avgr = new javax.swing.JLabel();
        avgwd = new javax.swing.JLabel();
        avgtd = new javax.swing.JLabel();
        avgrd = new javax.swing.JLabel();
        gant = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        P2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        exit3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BG.setBackground(new java.awt.Color(255, 255, 255));

        MID.setBackground(new java.awt.Color(255, 255, 255));
        MID.setLayout(new java.awt.CardLayout());

        P1.setBackground(new java.awt.Color(255, 255, 255));
        P1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                P1MouseDragged(evt);
            }
        });
        P1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                P1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                P1MouseReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Round Robin Schedule");

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Pic/close.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addComponent(exit)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exit)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        txtNoP.setBorder(null);
        txtNoP.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtNoP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNoPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNoPFocusLost(evt);
            }
        });

        sep1.setBackground(new java.awt.Color(240, 240, 240));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 118, 232));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Enter number of processes");

        jButton1.setBackground(new java.awt.Color(45, 118, 232));
        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(45, 118, 232));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Enter Quantum value");

        txtq.setBorder(null);
        txtq.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtq.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtqFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtqFocusLost(evt);
            }
        });

        sep2.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout P1Layout = new javax.swing.GroupLayout(P1);
        P1.setLayout(P1Layout);
        P1Layout.setHorizontalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(P1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P1Layout.createSequentialGroup()
                        .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNoP)
                            .addComponent(sep1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(128, 128, 128)
                        .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtq)
                            .addComponent(sep2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(P1Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P1Layout.setVerticalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtq, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sep1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sep2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 91, Short.MAX_VALUE))
        );

        MID.add(P1, "card2");

        P3.setBackground(new java.awt.Color(255, 255, 255));
        P3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                P3MouseDragged(evt);
            }
        });
        P3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                P3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                P3MouseReleased(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(45, 118, 232));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Round Robin Schedule");

        exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Pic/close.png"))); // NOI18N
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addComponent(exit1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exit1)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(45, 118, 232));
        jLabel7.setText("Process Name");

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(45, 118, 232));
        jLabel8.setText("Burst Time");

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(45, 118, 232));
        jLabel9.setText("Arrival Time");

        txtpname1.setBorder(null);
        txtpname1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpname1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpname1FocusLost(evt);
            }
        });

        txtpat1.setBorder(null);
        txtpat1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpat1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpat1FocusLost(evt);
            }
        });

        txtpbt1.setBorder(null);
        txtpbt1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpbt1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpbt1FocusLost(evt);
            }
        });

        txtpname2.setBorder(null);
        txtpname2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpname2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpname2FocusLost(evt);
            }
        });

        txtpname3.setBorder(null);
        txtpname3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpname3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpname3FocusLost(evt);
            }
        });

        txtpname4.setBorder(null);
        txtpname4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpname4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpname4FocusLost(evt);
            }
        });

        txtpname5.setBorder(null);
        txtpname5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpname5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpname5FocusLost(evt);
            }
        });

        txtpname6.setBorder(null);
        txtpname6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpname6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpname6FocusLost(evt);
            }
        });

        txtpname7.setBorder(null);
        txtpname7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpname7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpname7FocusLost(evt);
            }
        });

        txtpat2.setBorder(null);
        txtpat2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpat2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpat2FocusLost(evt);
            }
        });

        txtpat3.setBorder(null);
        txtpat3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpat3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpat3FocusLost(evt);
            }
        });

        txtpat4.setBorder(null);
        txtpat4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpat4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpat4FocusLost(evt);
            }
        });

        txtpat5.setBorder(null);
        txtpat5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpat5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpat5FocusLost(evt);
            }
        });

        txtpat6.setBorder(null);
        txtpat6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpat6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpat6FocusLost(evt);
            }
        });

        txtpat7.setBorder(null);
        txtpat7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpat7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpat7FocusLost(evt);
            }
        });

        txtpbt2.setBorder(null);
        txtpbt2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpbt2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpbt2FocusLost(evt);
            }
        });

        txtpbt3.setBorder(null);
        txtpbt3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpbt3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpbt3FocusLost(evt);
            }
        });

        txtpbt4.setBorder(null);
        txtpbt4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpbt4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpbt4FocusLost(evt);
            }
        });

        txtpbt5.setBorder(null);
        txtpbt5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpbt5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpbt5FocusLost(evt);
            }
        });

        txtpbt6.setBorder(null);
        txtpbt6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpbt6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpbt6FocusLost(evt);
            }
        });

        txtpbt7.setBorder(null);
        txtpbt7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpbt7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpbt7FocusLost(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(45, 118, 232));
        jButton2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P3Layout = new javax.swing.GroupLayout(P3);
        P3.setLayout(P3Layout);
        P3Layout.setHorizontalGroup(
            P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(P3Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(navname7)
                    .addComponent(txtpname7)
                    .addComponent(navname6)
                    .addComponent(txtpname6)
                    .addComponent(navname5)
                    .addComponent(txtpname5)
                    .addComponent(navname4)
                    .addComponent(txtpname4)
                    .addComponent(navname3)
                    .addComponent(txtpname3)
                    .addComponent(navname2)
                    .addComponent(txtpname2)
                    .addComponent(navname1)
                    .addComponent(txtpname1)
                    .addComponent(jLabel7))
                .addGap(74, 74, 74)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtpat7)
                    .addComponent(txtpat6)
                    .addComponent(txtpat5)
                    .addComponent(txtpat4)
                    .addComponent(txtpat3)
                    .addComponent(txtpat2)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtpat1)
                    .addComponent(navpat1)
                    .addComponent(navpat2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(navpat3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(navpat4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(navpat5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(navpat6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(navpat7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtpbt1)
                    .addComponent(navpbt1)
                    .addComponent(txtpbt2)
                    .addComponent(navpbt2)
                    .addComponent(txtpbt3)
                    .addComponent(navpbt3)
                    .addComponent(txtpbt4)
                    .addComponent(navpbt4)
                    .addComponent(txtpbt5)
                    .addComponent(navpbt5)
                    .addComponent(txtpbt6)
                    .addComponent(navpbt6)
                    .addComponent(txtpbt7)
                    .addComponent(navpbt7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P3Layout.setVerticalGroup(
            P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpbt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navname1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(navpat1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(navpbt1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(txtpname2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(navname2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(txtpat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(navpat2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(txtpbt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(navpbt2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(txtpname3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(navname3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(txtpat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(navpat3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(txtpbt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(navpbt3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(txtpname4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(navname4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(txtpat4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(navpat4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(txtpbt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(navpbt4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(txtpname5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(navname5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(txtpat5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(navpat5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(txtpbt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(navpbt5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(txtpname6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(navname6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(txtpat6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(navpat6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(txtpbt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(navpbt6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(txtpname7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(navname7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(txtpat7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(navpat7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P3Layout.createSequentialGroup()
                        .addComponent(txtpbt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(navpbt7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        MID.add(P3, "card2");

        P4.setBackground(new java.awt.Color(255, 255, 255));
        P4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                P4MouseDragged(evt);
            }
        });
        P4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                P4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                P4MouseReleased(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(45, 118, 232));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Round Robin Schedule");

        exit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Pic/close.png"))); // NOI18N
        exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addComponent(exit2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exit2)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel11.setText("Average Waiting Time");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel12.setText("Average Turn around Time");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel13.setText("Average Response Time");

        avgw.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        avgw.setForeground(new java.awt.Color(255, 0, 0));
        avgw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        avgt.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        avgt.setForeground(new java.awt.Color(255, 0, 0));
        avgt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        avgr.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        avgr.setForeground(new java.awt.Color(255, 0, 0));
        avgr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        avgwd.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        avgwd.setForeground(new java.awt.Color(45, 118, 232));
        avgwd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avgwd.setText("More details");
        avgwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avgwdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                avgwdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                avgwdMouseExited(evt);
            }
        });

        avgtd.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        avgtd.setForeground(new java.awt.Color(45, 118, 232));
        avgtd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avgtd.setText("More details");
        avgtd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avgtdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                avgtdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                avgtdMouseExited(evt);
            }
        });

        avgrd.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        avgrd.setForeground(new java.awt.Color(45, 118, 232));
        avgrd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avgrd.setText("More details");
        avgrd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avgrdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                avgrdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                avgrdMouseExited(evt);
            }
        });

        javax.swing.GroupLayout gantLayout = new javax.swing.GroupLayout(gant);
        gant.setLayout(gantLayout);
        gantLayout.setHorizontalGroup(
            gantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 934, Short.MAX_VALUE)
        );
        gantLayout.setVerticalGroup(
            gantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout P4Layout = new javax.swing.GroupLayout(P4);
        P4.setLayout(P4Layout);
        P4Layout.setHorizontalGroup(
            P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(P4Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(avgw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avgwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(avgt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avgtd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(143, 143, 143)
                .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avgr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avgrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(91, 91, 91))
            .addGroup(P4Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
            .addGroup(P4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(gant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P4Layout.setVerticalGroup(
            P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avgw, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avgt, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avgr, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avgwd)
                    .addComponent(avgtd)
                    .addComponent(avgrd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        MID.add(P4, "card2");

        P2.setBackground(new java.awt.Color(255, 255, 255));
        P2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                P2MouseDragged(evt);
            }
        });
        P2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                P2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                P2MouseReleased(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(45, 118, 232));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Round Robin Schedule");

        exit3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Pic/close.png"))); // NOI18N
        exit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addComponent(exit3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exit3)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Pic/Loading.gif"))); // NOI18N

        javax.swing.GroupLayout P2Layout = new javax.swing.GroupLayout(P2);
        P2.setLayout(P2Layout);
        P2Layout.setHorizontalGroup(
            P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(P2Layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P2Layout.setVerticalGroup(
            P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(58, 58, 58))
        );

        MID.add(P2, "card2");

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    Round_Robin rr = null;
    
    private void Assigntxtsep(){
        alltxt.add(txtpname1);
        alltxt.add(txtpat1);
        alltxt.add(txtpbt1);
        alltxt.add(txtpname2);
        alltxt.add(txtpat2);
        alltxt.add(txtpbt2);
        alltxt.add(txtpname3);
        alltxt.add(txtpat3);
        alltxt.add(txtpbt3);
        alltxt.add(txtpname4);
        alltxt.add(txtpat4);
        alltxt.add(txtpbt4);
        alltxt.add(txtpname5);
        alltxt.add(txtpat5);
        alltxt.add(txtpbt5);
        alltxt.add(txtpname6);
        alltxt.add(txtpat6);
        alltxt.add(txtpbt6);
        alltxt.add(txtpname7);
        alltxt.add(txtpat7);
        alltxt.add(txtpbt7);
        //-------------
        allsep.add(navname1);
        allsep.add(navpat1);
        allsep.add(navpbt1);
        allsep.add(navname2);
        allsep.add(navpat2);
        allsep.add(navpbt2);
        allsep.add(navname3);
        allsep.add(navpat3);
        allsep.add(navpbt3);
        allsep.add(navname4);
        allsep.add(navpat4);
        allsep.add(navpbt4);
        allsep.add(navname5);
        allsep.add(navpat5);
        allsep.add(navpbt5);
        allsep.add(navname6);
        allsep.add(navpat6);
        allsep.add(navpbt6);
        allsep.add(navname7);
        allsep.add(navpat7);
        allsep.add(navpbt7);
    }
    private void Hidden(){
        for(int i=0; i<21 ; i=i+3){
                alltxt.get(i).setVisible(false);
                alltxt.get(i+1).setVisible(false);
                alltxt.get(i+2).setVisible(false);
                allsep.get(i).setVisible(false);
                allsep.get(i+1).setVisible(false);
                allsep.get(i+2).setVisible(false);
        }
        
    }
    private void Show(int no){
        if(no>0 && no<=7){
            for(int i=0; i<no*3 ;i=i+3){
                alltxt.get(i).setVisible(true);
                alltxt.get(i+1).setVisible(true);
                alltxt.get(i+2).setVisible(true);
                allsep.get(i).setVisible(true);
                allsep.get(i+1).setVisible(true);
                allsep.get(i+2).setVisible(true);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "The number of process is from 1 to 7");
        }
        
    }
    private boolean SetProcesses(int no){
        String x="" ;
        String y ="";
        int yi = 0;
        String z ="";
        int zi = 0;
        int nset=0;
            for(int i=0; i<no*3 ;i=i+3){
                x = alltxt.get(i).getText();
                y = alltxt.get(i+1).getText();
                z = alltxt.get(i+2).getText();
                try{
                    yi = Integer.parseInt(y);
                    zi = Integer.parseInt(z);
                    if(yi<0 || zi<0){
                        JOptionPane.showMessageDialog(null,"Not allowed to set negative number");
                        return false;
                    }
                    if( !x.matches(".*\\w.*") ){
                        JOptionPane.showMessageDialog(null,"Not allowed to set process name empty");
                        return false;
                    }
                    rr.SetProcess(nset, x, yi, zi);
                    nset++;
                }
                catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Not allowed set Arrival time or Burst time empty or string");
                    return false;
                }
            }
            return true;
    }
    private void gantchart(){
    
        int size=0;
        int in=0;
        int out=0;        
        int arr[]={0,0,0,0,0,0,0};
        
        largepanel.setLayout(f);
        for(int i=0; i<rr.WaitingQueue.size() ; i++){
            name.add(new JLabel("   " + rr.WaitingQueue.get(i).getName()));
            
            name.get(i).setPreferredSize(new Dimension(30,15));
            
            smallpanal.add(new JPanel());
            //-------------------------------
            for(int ii=0;ii<rr.Processes.size();ii++){
                if(rr.WaitingQueue.get(i).getName() .equals(rr.Processes.get(ii).getName())){
                    in = rr.WaitingQueue.get(i).getIn().get(arr[ii]);
                    out = rr.WaitingQueue.get(i).getOut().get(arr[ii]);
                    arr[ii]++;
                    size=((out-in)*7)+80;
                }
            }
            //-------------------------------
            smallpanal.get(i).setPreferredSize(new Dimension(size,30));
                JLabel ins = new JLabel(String.valueOf(in));
                ins.setFont(new Font("Serif", Font.BOLD , 10));
                ins.setForeground(Color.white);
                ins.setPreferredSize(new Dimension(10,10));
                smallpanal.get(i).add(ins);
            smallpanal.get(i).add(name.get(i));
                JLabel outs = new JLabel(String.valueOf(out));
                outs.setFont(new Font("Serif", Font.BOLD, 10));
                outs.setForeground(Color.white);
                outs.setPreferredSize(new Dimension(10,10));
                smallpanal.get(i).add(outs);
            smallpanal.get(i).setBackground(Color.red);
            largepanel.add(smallpanal.get(i));
        }
        //largepanel.setPreferredSize(new Dimension(600,300));
        gant.setLayout(B);
        gant.setPreferredSize(new Dimension(934 , 168));
        gant.add(largepanel,B.CENTER);
        //largepanel.setBounds(1000, 1000, 1000, 10000);
        
    }
    
    
    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    int xx;
    int yy;
    
    private void P1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P1MousePressed
        // TODO add your handling code here:
        setOpacity((float)0.8);
        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_P1MousePressed

    private void P1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P1MouseReleased
        // TODO add your handling code here:
        setOpacity((float)1.0);
    }//GEN-LAST:event_P1MouseReleased

    private void P1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy );
    }//GEN-LAST:event_P1MouseDragged

    private void exit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit2MouseClicked

    private void P4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P4MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy );
    }//GEN-LAST:event_P4MouseDragged

    private void P4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P4MousePressed
        // TODO add your handling code here:
        setOpacity((float)0.8);
        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_P4MousePressed

    private void P4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P4MouseReleased
        // TODO add your handling code here:
        setOpacity((float)1.0);
    }//GEN-LAST:event_P4MouseReleased

    private void exit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit3MouseClicked

    private void P2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy );
    }//GEN-LAST:event_P2MouseDragged

    private void P2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P2MousePressed
        // TODO add your handling code here:
        setOpacity((float)0.8);
        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_P2MousePressed

    private void P2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P2MouseReleased
        // TODO add your handling code here:
        setOpacity((float)1.0);
    }//GEN-LAST:event_P2MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String noop="";
        String qu="";
        noop= txtNoP.getText();
        qu = txtq.getText();
        int noopi=0;
        int qui=0;
        try {
            noopi=Integer.parseInt(noop);
            qui=Integer.parseInt(qu);
        }
            
        catch(Exception x){
            JOptionPane.showMessageDialog(null, "Not allowed to enter empty or string value");
        }
        
        if (noopi > 0 && noopi <= 7 && qui > 0){
            rr = new Round_Robin(noopi, qui);
            Show(noopi);
            P3.show();
            P1.hide();
        }
        else{
            JOptionPane.showMessageDialog(null, "The number of processe should be positive and from 1 to 7 and Quantum should be positive");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void P3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P3MouseReleased
        // TODO add your handling code here:
        setOpacity((float)1.0);
    }//GEN-LAST:event_P3MouseReleased

    private void P3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P3MousePressed
        // TODO add your handling code here:
        setOpacity((float)0.8);
        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_P3MousePressed

    private void P3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P3MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy );
    }//GEN-LAST:event_P3MouseDragged

    private void exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit1MouseClicked

    private void txtpname1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpname1FocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtpname1.setBackground(cl);
    }//GEN-LAST:event_txtpname1FocusGained

    private void txtpname1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpname1FocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtpname1.setBackground(cl);
    }//GEN-LAST:event_txtpname1FocusLost

    private void txtpat1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpat1FocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtpat1.setBackground(cl);
    }//GEN-LAST:event_txtpat1FocusGained

    private void txtpat1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpat1FocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtpat1.setBackground(cl);
    }//GEN-LAST:event_txtpat1FocusLost

    private void txtpbt1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpbt1FocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtpbt1.setBackground(cl);
    }//GEN-LAST:event_txtpbt1FocusGained

    private void txtpbt1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpbt1FocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtpbt1.setBackground(cl);
    }//GEN-LAST:event_txtpbt1FocusLost

    private void txtpname2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpname2FocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtpname2.setBackground(cl);
    }//GEN-LAST:event_txtpname2FocusGained

    private void txtpname2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpname2FocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtpname2.setBackground(cl);
    }//GEN-LAST:event_txtpname2FocusLost

    private void txtpname3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpname3FocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtpname3.setBackground(cl);
    }//GEN-LAST:event_txtpname3FocusGained

    private void txtpname3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpname3FocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtpname3.setBackground(cl);
    }//GEN-LAST:event_txtpname3FocusLost

    private void txtpname4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpname4FocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtpname4.setBackground(cl);
    }//GEN-LAST:event_txtpname4FocusGained

    private void txtpname4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpname4FocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtpname4.setBackground(cl);
    }//GEN-LAST:event_txtpname4FocusLost

    private void txtpname5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpname5FocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtpname5.setBackground(cl);
    }//GEN-LAST:event_txtpname5FocusGained

    private void txtpname5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpname5FocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtpname5.setBackground(cl);
    }//GEN-LAST:event_txtpname5FocusLost

    private void txtpname6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpname6FocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtpname6.setBackground(cl);
    }//GEN-LAST:event_txtpname6FocusGained

    private void txtpname6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpname6FocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtpname6.setBackground(cl);
    }//GEN-LAST:event_txtpname6FocusLost

    private void txtpname7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpname7FocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtpname7.setBackground(cl);
    }//GEN-LAST:event_txtpname7FocusGained

    private void txtpname7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpname7FocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtpname7.setBackground(cl);
    }//GEN-LAST:event_txtpname7FocusLost

    private void txtpat2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpat2FocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtpat2.setBackground(cl);
    }//GEN-LAST:event_txtpat2FocusGained

    private void txtpat2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpat2FocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtpat2.setBackground(cl);
    }//GEN-LAST:event_txtpat2FocusLost

    private void txtpat3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpat3FocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtpat3.setBackground(cl);
    }//GEN-LAST:event_txtpat3FocusGained

    private void txtpat3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpat3FocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtpat3.setBackground(cl);
    }//GEN-LAST:event_txtpat3FocusLost

    private void txtpat4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpat4FocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtpat4.setBackground(cl);
    }//GEN-LAST:event_txtpat4FocusGained

    private void txtpat4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpat4FocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtpat4.setBackground(cl);
    }//GEN-LAST:event_txtpat4FocusLost

    private void txtpat5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpat5FocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtpat5.setBackground(cl);
    }//GEN-LAST:event_txtpat5FocusGained

    private void txtpat5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpat5FocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtpat5.setBackground(cl);
    }//GEN-LAST:event_txtpat5FocusLost

    private void txtpat6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpat6FocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtpat6.setBackground(cl);
    }//GEN-LAST:event_txtpat6FocusGained

    private void txtpat6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpat6FocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtpat6.setBackground(cl);
    }//GEN-LAST:event_txtpat6FocusLost

    private void txtpat7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpat7FocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtpat7.setBackground(cl);
    }//GEN-LAST:event_txtpat7FocusGained

    private void txtpat7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpat7FocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtpat7.setBackground(cl);
    }//GEN-LAST:event_txtpat7FocusLost

    private void txtpbt2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpbt2FocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtpbt2.setBackground(cl);
    }//GEN-LAST:event_txtpbt2FocusGained

    private void txtpbt2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpbt2FocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtpbt2.setBackground(cl);
    }//GEN-LAST:event_txtpbt2FocusLost

    private void txtpbt3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpbt3FocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtpbt3.setBackground(cl);
    }//GEN-LAST:event_txtpbt3FocusGained

    private void txtpbt3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpbt3FocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtpbt3.setBackground(cl);
    }//GEN-LAST:event_txtpbt3FocusLost

    private void txtpbt4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpbt4FocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtpbt4.setBackground(cl);
    }//GEN-LAST:event_txtpbt4FocusGained

    private void txtpbt4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpbt4FocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtpbt4.setBackground(cl);
    }//GEN-LAST:event_txtpbt4FocusLost

    private void txtpbt5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpbt5FocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtpbt5.setBackground(cl);
    }//GEN-LAST:event_txtpbt5FocusGained

    private void txtpbt5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpbt5FocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtpbt5.setBackground(cl);
    }//GEN-LAST:event_txtpbt5FocusLost

    private void txtpbt6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpbt6FocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtpbt6.setBackground(cl);
    }//GEN-LAST:event_txtpbt6FocusGained

    private void txtpbt6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpbt6FocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtpbt6.setBackground(cl);
    }//GEN-LAST:event_txtpbt6FocusLost

    private void txtpbt7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpbt7FocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtpbt7.setBackground(cl);
    }//GEN-LAST:event_txtpbt7FocusGained

    private void txtpbt7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpbt7FocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtpbt7.setBackground(cl);
    }//GEN-LAST:event_txtpbt7FocusLost

    private void txtNoPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNoPFocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtNoP.setBackground(cl);
    }//GEN-LAST:event_txtNoPFocusGained

    private void txtNoPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNoPFocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtNoP.setBackground(cl);
    }//GEN-LAST:event_txtNoPFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(SetProcesses(rr.NoOfProcesses())){
            rr.SortProcess();
            rr.Run_RR();
            
            avgw.setText(String.valueOf(rr.AVGWaitingTime()) + " " + "ms");
            avgt.setText(String.valueOf(rr.AVGTurnAroundTime()) + " " + "ms");
            avgr.setText(String.valueOf(rr.AVGResponsedTime())  + " " + "ms");
            
            gantchart();

            P2.show();
            P3.hide();

            // timer

            new java.util.Timer().schedule(new TimerTask() {
                @Override
                public void run() {
                    P2.hide();
                    P4.show();
                }
            },1000*1);}
        else{
            //JOptionPane.showMessageDialog(null, "not allowed set Arrival time or Burst time empty or string");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtqFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtqFocusGained
        // TODO add your handling code here:
        Color cl = new Color(153,255,255);
        txtq.setBackground(cl);
    }//GEN-LAST:event_txtqFocusGained

    private void txtqFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtqFocusLost
        // TODO add your handling code here:
        Color cl = new Color(255,255,255);
        txtq.setBackground(cl);
    }//GEN-LAST:event_txtqFocusLost

    private void avgwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avgwdMouseClicked
        // TODO add your handling code here:
        String wdt ="";
        for(int i=0; i<rr.Processes.size();i++){
            wdt = wdt + rr.Processes.get(i).getName() + "= " + String.valueOf(rr.WaitingTime(i)) + " ms" +  " \n";
        }
        JOptionPane.showMessageDialog(null ,"The details for waiting time is:"+ "\n\n" + wdt);
    }//GEN-LAST:event_avgwdMouseClicked

    private void avgtdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avgtdMouseClicked
        // TODO add your handling code here:
        String tdt ="";
        for(int i=0; i<rr.Processes.size();i++){
            tdt = tdt + rr.Processes.get(i).getName() + "= " + String.valueOf(rr.TurnAroundTime(i)) + " ms" +  " \n";
        }
        JOptionPane.showMessageDialog(null ,"The details for Turn around time is:"+ "\n\n" + tdt);
    }//GEN-LAST:event_avgtdMouseClicked

    private void avgrdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avgrdMouseClicked
        // TODO add your handling code here:
        String rdt ="";
        for(int i=0; i<rr.Processes.size();i++){
            rdt = rdt + rr.Processes.get(i).getName() + "= " + String.valueOf(rr.ResponseTime(i)) + " ms" +  " \n";
        }
        JOptionPane.showMessageDialog(null ,"The details for Response time is:"+ "\n\n" + rdt);
    }//GEN-LAST:event_avgrdMouseClicked

    private void avgwdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avgwdMouseEntered
        // TODO add your handling code here:
        avgwd.setForeground(Color.blue);
    }//GEN-LAST:event_avgwdMouseEntered

    private void avgwdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avgwdMouseExited
        // TODO add your handling code here:
        Color cavg = new Color(45,118,232);
        avgwd.setForeground(cavg);
    }//GEN-LAST:event_avgwdMouseExited

    private void avgtdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avgtdMouseEntered
        // TODO add your handling code here:
        avgtd.setForeground(Color.blue);
    }//GEN-LAST:event_avgtdMouseEntered

    private void avgtdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avgtdMouseExited
        // TODO add your handling code here:
        Color cavg = new Color(45,118,232);
        avgtd.setForeground(cavg);
    }//GEN-LAST:event_avgtdMouseExited

    private void avgrdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avgrdMouseEntered
        // TODO add your handling code here:
        avgrd.setForeground(Color.blue);
    }//GEN-LAST:event_avgrdMouseEntered

    private void avgrdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avgrdMouseExited
        // TODO add your handling code here:
        Color cavg = new Color(45,118,232);
        avgrd.setForeground(cavg);
    }//GEN-LAST:event_avgrdMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel MID;
    private javax.swing.JPanel P1;
    private javax.swing.JPanel P2;
    private javax.swing.JPanel P3;
    private javax.swing.JPanel P4;
    private javax.swing.JLabel avgr;
    private javax.swing.JLabel avgrd;
    private javax.swing.JLabel avgt;
    private javax.swing.JLabel avgtd;
    private javax.swing.JLabel avgw;
    private javax.swing.JLabel avgwd;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exit1;
    private javax.swing.JLabel exit2;
    private javax.swing.JLabel exit3;
    private javax.swing.JPanel gant;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator navname1;
    private javax.swing.JSeparator navname2;
    private javax.swing.JSeparator navname3;
    private javax.swing.JSeparator navname4;
    private javax.swing.JSeparator navname5;
    private javax.swing.JSeparator navname6;
    private javax.swing.JSeparator navname7;
    private javax.swing.JSeparator navpat1;
    private javax.swing.JSeparator navpat2;
    private javax.swing.JSeparator navpat3;
    private javax.swing.JSeparator navpat4;
    private javax.swing.JSeparator navpat5;
    private javax.swing.JSeparator navpat6;
    private javax.swing.JSeparator navpat7;
    private javax.swing.JSeparator navpbt1;
    private javax.swing.JSeparator navpbt2;
    private javax.swing.JSeparator navpbt3;
    private javax.swing.JSeparator navpbt4;
    private javax.swing.JSeparator navpbt5;
    private javax.swing.JSeparator navpbt6;
    private javax.swing.JSeparator navpbt7;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    private javax.swing.JTextField txtNoP;
    private javax.swing.JTextField txtpat1;
    private javax.swing.JTextField txtpat2;
    private javax.swing.JTextField txtpat3;
    private javax.swing.JTextField txtpat4;
    private javax.swing.JTextField txtpat5;
    private javax.swing.JTextField txtpat6;
    private javax.swing.JTextField txtpat7;
    private javax.swing.JTextField txtpbt1;
    private javax.swing.JTextField txtpbt2;
    private javax.swing.JTextField txtpbt3;
    private javax.swing.JTextField txtpbt4;
    private javax.swing.JTextField txtpbt5;
    private javax.swing.JTextField txtpbt6;
    private javax.swing.JTextField txtpbt7;
    private javax.swing.JTextField txtpname1;
    private javax.swing.JTextField txtpname2;
    private javax.swing.JTextField txtpname3;
    private javax.swing.JTextField txtpname4;
    private javax.swing.JTextField txtpname5;
    private javax.swing.JTextField txtpname6;
    private javax.swing.JTextField txtpname7;
    private javax.swing.JTextField txtq;
    // End of variables declaration//GEN-END:variables
}
