/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panal;

import Classes.Employee;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ATHER
 */
public class AdminListEmp extends javax.swing.JPanel {

    /**
     * Creates new form AdminListEmp
     */
    public AdminListEmp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmp = new javax.swing.JTable();

        setBackground(new java.awt.Color(32, 47, 90));
        setMaximumSize(new java.awt.Dimension(870, 376));
        setMinimumSize(new java.awt.Dimension(870, 376));

        jScrollPane1.setBackground(new java.awt.Color(32, 47, 90));

        tblEmp.setBackground(new java.awt.Color(32, 47, 90));
        tblEmp.setForeground(new java.awt.Color(204, 204, 204));
        tblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Birth Date", "Gender", "Phone", "Address", "Qualification", "Join Date", "UserName", "PassWord"
            }
        ));
        tblEmp.setGridColor(new java.awt.Color(204, 204, 204));
        tblEmp.getTableHeader().setResizingAllowed(false);
        tblEmp.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblEmp);
        if (tblEmp.getColumnModel().getColumnCount() > 0) {
            tblEmp.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

      DefaultTableModel model;
    
    public void ClearTable(){
        model = (DefaultTableModel) tblEmp.getModel();
        model.setRowCount(0);
    }
    
    public void ListTable() {
        model = (DefaultTableModel) tblEmp.getModel();
        
        Object rowData[] = new Object[10];
        Employee cu = new Employee();
        ArrayList<Employee> Cust = new ArrayList<Employee>();
        
        Cust= cu.listEmployee();

        for (Employee x : Cust) {
            rowData[0] = x.getID();
            rowData[1] = x.getName();
            rowData[2] = x.getDateOfBirth();
            rowData[3] = x.getGender();
            rowData[4] = x.getPhoneNo();
            rowData[5] = x.getAddress();
            rowData[6] = x.getQualification();
            rowData[7] = x.getDateOfJoining();
            rowData[8] = x.getUserName();
            rowData[9] = x.getPassword();
            

            model.addRow(rowData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmp;
    // End of variables declaration//GEN-END:variables
}
