/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panal;

import Classes.Customers;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ATHER
 */
public class EmployeeListCust extends javax.swing.JPanel {

    /**
     * Creates new form AdminListEmp
     */
    public EmployeeListCust() {
        initComponents();
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCust = new javax.swing.JTable();

        setBackground(new java.awt.Color(32, 47, 90));
        setMaximumSize(new java.awt.Dimension(870, 376));
        setMinimumSize(new java.awt.Dimension(870, 376));

        jScrollPane1.setBackground(new java.awt.Color(32, 47, 90));

        tblCust.setBackground(new java.awt.Color(32, 47, 90));
        tblCust.setForeground(new java.awt.Color(204, 204, 204));
        tblCust.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "First Name", "Last Name", "Gender", "Phone", "Address", "Birth Date"
            }
        ));
        tblCust.setGridColor(new java.awt.Color(204, 204, 204));
        tblCust.getTableHeader().setResizingAllowed(false);
        tblCust.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblCust);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    DefaultTableModel model;
    
    public void ClearTable(){
        model = (DefaultTableModel) tblCust.getModel();
        model.setRowCount(0);
    }
    
    public void ListTable() {
        model = (DefaultTableModel) tblCust.getModel();
        
        Object rowData[] = new Object[7];
        Customers cu = new Customers();
        ArrayList<Customers> Cust = new ArrayList<Customers>();
        
        Cust= cu.listCustomer();

        for (Customers x : Cust) {
            rowData[0] = x.getCustomer_id();
            rowData[1] = x.getFirst_name();
            rowData[2] = x.getLast_name();
            rowData[3] = x.getCustomer_gender();
            rowData[4] = x.getCustomer_Phone();
            rowData[5] = x.getCustomer_Adress();
            rowData[6] = x.getCustomer_DOB();
            

            model.addRow(rowData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCust;
    // End of variables declaration//GEN-END:variables
}
